name: Run tests in SmallTalk
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: Run tests
        run: ./.github/workflows/runTests.sh MarsRover MarsRoverTest
